# x=int(input())
# print(x)
# print(type(x))
# y=float(input())
# print(y)
# print(type(y))
# z=str(input())
# print(z)
# print(type(z))

x=int(input("1st value= "))
y=int(input("2nd value= "))
print(x+y,x-y,x*y,x/y,x//y,x%y)